SupplyManagementSystem/Models/Order.cs
using SCM.Core;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SCM.Models
{
    public class Order : Entity
    {
        [DisplayName("Наименование заказа")]
        public new string Title { set; get; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Дата оформления заказа")]
        public DateTime Date { set; get; }


        [NotMapped]
        public string FormatDate => GetDate();

        private string GetDate()
        {
            return Date.ToShortDateString();
        }

        [DisplayName("Статус заказа")]
        public bool IsFinished { set; get; }

        [NotMapped]
        public string IsFinishedAsString => GetStatus();

        private string GetStatus()
        {
            return IsFinished ? "Завершен": "Не завершен";
        }

        /// <summary>
        /// Образцы в заказе
        /// </summary>
        public ICollection<OrdersSample> OrdersSamples { get; set; }
        
        [DisplayName("Организация заказщика")]
        public string OrganizationClient { set; get; }
        
        
        /// <summary>
        /// Объект химического состава, из которого состоит образец
        /// </summary>
        public virtual ChemicalComposition ChemicalComposition { get; set; }

        /// <summary>
        /// Вторичный ключ для связи с химическим составом. Не может отсутствовать
        /// </summary>
        [ForeignKey(nameof(ChemicalComposition))]
        [DisplayName("Химический состав")]
        [Required(ErrorMessage = "Обязательное поле")]
        public int ChemicalCompositionId { get; set; }
    }
}

SupplyManagementSystem/ViewModels/Clients/OrderViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SCM.ViewModels.Clients
{
    public class OrderViewModel
    {
        [Required(ErrorMessage = "Обязательное поле")]
        public string City { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        public string Phone { get; set; }
        
        public string Comment { get; set; }
        
        
        [DisplayName("Согласие на обработку персональных данных")]
        [Required(ErrorMessage = "Обязательное поле")]
        public bool PersonalDataAgreement { get; set; }
    }
}

SupplyManagementSystem/ViewModels/Order/FullOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SCM.ViewModels.Samples;

namespace SCM.ViewModels.Order
{
    public class FullOrderViewModel
    {

        [DisplayName("Клиент")]
        public string ClientTitle { get; set; }
        public int ClientId { get; set; }
        public List<SampleOrderModel> Samples { get; set; }
        
        [DisplayName("Наименование заказа")]
        public string Title { get; set; }
        
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Дата оформления заказа")]
        public DateTime CreationDateTime { get; set; }

        
    }
}

SupplyManagementSystem/ViewModels/Order/OrderGridModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using SCM.Models;

namespace SCM.ViewModels.Order
{
    public class OrderGridModel
    {

        public int Id { get; set; }
        [DisplayName("Наименование заказа")]
        public new string Title { set; get; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Дата оформления заказа")]
        public DateTime Date { set; get; }

        [NotMapped]
        public string FormatDate => GetDate();

        private string GetDate()
        {
            return Date.ToShortDateString();
        }

        [DisplayName("Статус заказа")]
        public bool IsFinished { set; get; }

        [NotMapped]
        public string IsFinishedAsString => GetStatus();

        private string GetStatus()
        {
            return IsFinished ? "Завершен": "Не завершен";
        }


        public string ClientOrganization { get; set; }
        
        
    }
}

SupplyManagementSystem/ViewModels/Order/SimpleOrderViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SCM.ViewModels.Order
{
    public class SimpleOrderViewModel
    {
        [Required(ErrorMessage = "Обязательное поле")]
        public int ClientId { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Образцы")]
        public int[] SampleId { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DisplayName("Наименование заказа")]
        public string Title { get; set; }
        
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Дата оформления заказа")]
        
        public DateTime CreationDateTime { get; set; }
        
    }
}

SupplyManagementSystem/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using SCM.DataService.DataContext;
using SCM.Models;
using SCM.ViewModels.Order;
using SCM.ViewModels.Samples;

namespace SCM.Controllers
{
    public class OrdersController : Controller
    {
        private AppDataContext db = new AppDataContext();

        // GET: Orders
        public ActionResult Index(int? clientId)
        {
            var dbOrders = db.Orders.AsQueryable();
            var client = db.Clients.FirstOrDefault(c => c.Id == clientId);
            var clientName =client == null? null : $"{client?.Name} - {client?.Organization}";
            if (clientId.HasValue) dbOrders = dbOrders.Where(o => o.ClientId == clientId);

            var orders = dbOrders.Select(s => new OrderGridModel()
            {
                Id = s.Id,
                Date = s.Date,
                Title = s.Title,
                IsFinished = s.IsFinished,
                ClientOrganization = s.Client.Organization
            }).ToList();

            ViewBag.ClientId = clientId;
            ViewBag.ClientName = clientName;
            return View(orders);
        }

        public ActionResult OrdersRead([DataSourceRequest] DataSourceRequest request, int? clientId)
        {
            ViewBag.ClientId = clientId;
            var dbOrders = db.Orders.AsQueryable();
            if (clientId.HasValue) dbOrders = dbOrders.Where(o => o.ClientId == clientId);
            
            var orders = dbOrders.Select(s => new OrderGridModel()
            {
                Id = s.Id,
                Date = s.Date,
                Title = s.Title,
                IsFinished = s.IsFinished,
                ClientOrganization = s.Client.Organization
            }).ToList();
            return Json(orders.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }


        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.ClientId =
                new SelectList(db.Clients.ToList().Select(s => new {Id = s.Id, Name = $"{s.Name} - {s.Organization}"}),
                    "Id", "Name");


            var accessableSamples = db.Samples.Where(s => s.Amount >= 1).Select(sample => new SelectListItem()
                {Text = sample.Title, Value = sample.Id.ToString()}).OrderBy(option => option.Text);
            var samples = new MultiSelectList(accessableSamples, "Value", "Text");

            ViewBag.SampleId = samples;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateStageOne(SimpleOrderViewModel order)
        {
            ViewBag.ClientId =
                new SelectList(db.Clients.ToList().Select(s => new {Id = s.Id, Name = $"{s.Name} - {s.Organization}"}),
                    "Id", "Name");

            var accessableSamples = db.Samples.Where(s => s.Amount >= 1).Select(sample => new SelectListItem()
                {Text = sample.Title, Value = sample.Id.ToString()}).OrderBy(option => option.Text);
            var samplesId = new MultiSelectList(accessableSamples, "Value", "Text");

            ViewBag.SampleId = samplesId;
            if (!ModelState.IsValid)
                return PartialView("Partials/CreateFirstStep", order);

            var client = db.Clients.FirstOrDefault(c => c.Id == order.ClientId);
            var samples = db.Samples.Where(s => order.SampleId.Contains(s.Id)).Select(s => new SampleOrderModel
            {
                InStock = s.Amount,
                Amount = 1,
                Title = s.Title,
                SampleId = s.Id
            }).ToList();
            var fullOrderModel = new FullOrderViewModel();
            fullOrderModel.Samples = samples;
            fullOrderModel.Title = order.Title;
            fullOrderModel.CreationDateTime = DateTime.Now;
            fullOrderModel.ClientId = order.ClientId;
            fullOrderModel.ClientTitle = $"{client.Name} - {client.Organization}";

            return PartialView("Partials/CreateSecondStep", fullOrderModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateStageTwo(FullOrderViewModel model)
        {
            var valid = true;
            List<string> errored = new List<string>();
            foreach (var sample in model.Samples)
            {
                var dbSample = db.Samples.FirstOrDefault(s => s.Id == sample.SampleId);
                if (dbSample.Amount < sample.Amount)
                {
                    errored.Add(sample.Title);
                    valid = false;
                }
            }

            var concatErrored = string.Join(", ", errored);
            if (!valid)
            {
                var insertion = concatErrored.Length == 1 ? "имеет" : "имеют";
                ViewBag.Message = $"Образцы {concatErrored} {insertion} неверное количество!";
                ModelState.AddModelError("Samples", "Какой-то из образцов имеет недопустимое количество");
            }

            if (!ModelState.IsValid)
                return PartialView("Partials/CreateSecondStep", model);

            var order = new Order();
            order.Title = model.Title;
            order.Client = db.Clients.FirstOrDefault(c => c.Id == model.ClientId);
            order.Date = DateTime.Now;
            db.Orders.Add(order);
            db.SaveChanges();

            foreach (var sample in model.Samples)
            {
                var dbSample = db.Samples.FirstOrDefault(s => s.Id == sample.SampleId);
                dbSample.Amount = dbSample.Amount - sample.Amount;
                var link = new OrdersSample();
                link.Order = order;
                link.OrderId = order.Id;
                link.Sample = dbSample;
                link.SampleId = dbSample.Id;
                link.Amount = sample.Amount;
                db.Add(link);
            }

            db.SaveChanges();

            var successMarkup = "<div class=\"container\"><h3>Успешно!</h3>" +
                                "<p>Заказ поступил в обработку.</p></div>";
            return Content(successMarkup);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }

            ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", order.ClientId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Date,IsFinished,ClientId")]
            Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClientId = new SelectList(db.Clients, "Id", "Name", order.ClientId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);

            var links = db.OrdersSamples.Where( r=> r.OrderId == order.Id).ToList();
            foreach (var link in links) db.OrdersSamples.Remove(link);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

SupplyManagementSystem/Views/Orders/Partials/CreateFirstStep.cshtml
@model SCM.ViewModels.Order.SimpleOrderViewModel
@{
    var samplesToSelect = (MultiSelectList) ViewBag.SampleId;
}

@using (Ajax.BeginForm("CreateStageOne", "Orders", new AjaxOptions {HttpMethod = "POST", UpdateTargetId = "wizard", OnSuccess = ""}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Заказ. Шаг 1</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "Заказчик", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control chosen-select" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SampleId, htmlAttributes: new { @class = "control-label col-md-6" })
            <div class="col-md-12">
                @Html.ListBoxFor(m => m.SampleId, samplesToSelect, new { multiple = "multiple", @class = "chosen-select", placeholder = "Выберите элементы" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Продолжить" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script>
$(document).ready(function () {

    $(".chosen-select").chosen({
         width: "100%",
        no_results_text: "Ничего не найдено",
        placeholder_text_multiple: "Выберите несколько параметров",
    });
});
</script>

SupplyManagementSystem/Views/Orders/Partials/CreateSecondStep.cshtml
@using System.ServiceModel.Channels
@model SCM.ViewModels.Order.FullOrderViewModel
@{
    var message = (string) ViewBag.Message;
}
@using (Ajax.BeginForm("CreateStageTwo", "Orders", new AjaxOptions {HttpMethod = "POST", UpdateTargetId = "wizard", OnSuccess = ""}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Заказ. Шаг 2</h4>
        <hr/>
        @Html.ValidationSummary(true, message, new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control", @disabled = "disabled"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>
        @Html.HiddenFor(model => model.Title)

        <div class="form-group">
            @Html.LabelFor(model => model.ClientTitle, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClientTitle, new {htmlAttributes = new {@class = "form-control", @disabled = "disabled"}})
                @Html.ValidationMessageFor(model => model.ClientTitle, "", new {@class = "text-danger"})
            </div>
        </div>
        @Html.HiddenFor(model => model.ClientId)
        @Html.HiddenFor(model => model.ClientTitle)

        @for (var index = 0; index < Model.Samples.Count; index++)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Samples[index].Amount, $"Кол-во образца {Model.Samples[index].Title}", htmlAttributes: new {@class = "control-label col-md-6"})
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Samples[index].Amount, new {htmlAttributes = new {@class = "form-control", aria_describedby = $"sample-description-{index}"}})
                    <small id="sample-description-@(index)" class="form-text text-muted">Доступно для заказа @(Model.Samples[index].InStock)</small>
                    @Html.ValidationMessageFor(model => model.Samples[index].Amount, "", new {@class = "text-danger"})
                </div>
            </div>

            @Html.HiddenFor(model => model.Samples[index].SampleId)
            @Html.HiddenFor(model => model.Samples[index].Title)
            @Html.HiddenFor(model => model.Samples[index].InStock)
            @Html.HiddenFor(model => model.Samples[index].Amount)
           
        }


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<script>
$(document).ready(function () {

    $(".chosen-select").chosen({
         width: "100%",
        no_results_text: "Ничего не найдено",
        placeholder_text_multiple: "Выберите несколько параметров",
    });
});
</script>