SupplyManagementSystem/Models/Sample.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using SCM.Core;

namespace SCM.Models
{
    public class Sample : Entity
    {
        [Display(Name = "Название")]
        public new string Title { get; set; }
        /// <summary>
        /// Объект химического состава, из которого состоит образец
        /// </summary>
        public virtual ChemicalComposition ChemicalComposition { get; set; }

        /// <summary>
        /// Вторичный ключ для связи с химическим составом. Не может отсутствовать
        /// </summary>
        [ForeignKey(nameof(ChemicalComposition))]
        [DisplayName("Химический состав")]
        [Required(ErrorMessage = "Обязательное поле")]
        public int ChemicalCompositionId { get; set; }
        
        

        /// <summary>
        /// Заказы, в которых участвовал данный образец
        /// </summary>
        public virtual ICollection<OrdersSample> OrdersSamples { get; set; }
        
        /// <summary>
        /// Количество образца на складе
        /// </summary>
        [Display(Name = "Количество")]
        [Range(0, 10000, ErrorMessage = "Количество должно быть в диапазоне 0 - 10000")]
        public int Amount { get; set; }
        
        [DisplayName("Ссылка на изображение")]
        public string ImageLink { get; set; }

        [DisplayName("Вес образца, г.")]
        [Range(0, 10000, ErrorMessage = "Вес должен быть в диапазоне 0 - 10000")]
        public double Weight { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Срок годности")]
        public DateTime ExpiryDate { get; set; }

        [NotMapped]
        public string FormatDate => GetFormatDate();

        private string GetFormatDate()
        {
            return ExpiryDate.ToShortDateString();
        }

        [NotMapped]
        public string ChemicalCompositionAsString => FormatChemicalComposition();

        private string FormatChemicalComposition()
        {
            return this.ChemicalComposition.Title;
        }
    }
}

SupplyManagementSystem/ViewModels/Samples/SampleOrderModel.cs
using System.ComponentModel.DataAnnotations;

namespace SCM.ViewModels.Samples
{
    public class SampleOrderModel
    {

        public string Title { get; set; }
        public int SampleId { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [Range(1, 10000, ErrorMessage = "От 1 до 10000")]
        public int Amount { get; set; }
        
        public int InStock { get; set; }
    }
}

SupplyManagementSystem/ViewModels/Samples/SamplesGridModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
using SCM.Models;

namespace SCM.ViewModels.Samples
{
    public class SamplesGridModel
    {

        public int Id { get; set; }
        
        [Display(Name = "Название")]
        public string Title { get; set; }
        
        [Display(Name = "Количество")]
        [Range(0, 10000, ErrorMessage = "Количество должно быть в диапазоне 0 - 10000")]
        public int Amount { get; set; }
        
        [DisplayName("Ссылка на изображение")]
        public string ImageLink { get; set; }

        [DisplayName("Вес образца")]
        [Range(0, 10000, ErrorMessage = "Вес должен быть в диапазоне 0 - 10000")]
        public double Weight { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Срок годности")]
        public DateTime ExpiryDate { get; set; }

        public string FormatDate => GetFormatDate();

        private string GetFormatDate()
        {
            return ExpiryDate.ToShortDateString();
        }
        public string ChemicalCompositionAsString { get; set; }

        
    }
}

SupplyManagementSystem/Controllers/ExcelController.cs
using System;
using System.Web.Mvc;

namespace SCM.Controllers
{
    public class ExcelController : Controller
    {
        
        [HttpPost]
        public ActionResult ExportExcel(string contentType, string base64, string fileName)
        {
            var fileContents = Convert.FromBase64String(base64);
            return File(fileContents, contentType, fileName);
        }
    }
}

SupplyManagementSystem/Controllers/SamplesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using SCM.DataService.DataContext;
using SCM.Models;
using SCM.ViewModels.Samples;

namespace SCM.Controllers
{
    [Authorize]
    public class SamplesController : Controller
    {
        private AppDataContext db = new AppDataContext();

        // GET: Samples
        public ActionResult Index()
        {
           var samples = db.Samples.Select(s => new SamplesGridModel()
                      {
                          Id = s.Id,
                          Amount = s.Amount,
                          ChemicalCompositionAsString = s.ChemicalComposition.Title,
                          ExpiryDate = s.ExpiryDate,
                          ImageLink = s.ImageLink,
                          Title = s.Title,
                          Weight = s.Weight
                      });
            return View(samples.ToList());
        }
        
        public ActionResult SamplesRead([DataSourceRequest]DataSourceRequest request)
        {
            var context = new AppDataContext();
            var samples = context.Samples.Select(s => new SamplesGridModel()
            {
                Id = s.Id,
                Amount = s.Amount,
                ChemicalCompositionAsString = s.ChemicalComposition.Title,
                ExpiryDate = s.ExpiryDate,
                ImageLink = s.ImageLink,
                Title = s.Title,
                Weight = s.Weight
            }).ToList();
            return Json(samples.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        // GET: Samples/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sample sample = db.Samples.Find(id);
            if (sample == null)
            {
                return HttpNotFound();
            }
            return View(sample);
        }

        // GET: Samples/Create
        public ActionResult Create(int? categoryId)
        {
            if (categoryId.HasValue)
            {
                ViewBag.ChemicalCompositionId = new SelectList(db.ChemicalCompositions.Where(c=> c.SampleCategoryId == categoryId), "Id", "Title"); 
            }
            else
            {
                ViewBag.ChemicalCompositionId = new SelectList(db.ChemicalCompositions, "Id", "Title");   
            }
            
            return View();
        }

        // POST: Samples/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,ChemicalCompositionId,Amount,ImageLink,Weight,ExpiryDate")] Sample sample)
        {
            if (ModelState.IsValid)
            {

                db.Samples.Add(sample);
                db.SaveChanges();
                return RedirectToAction("Index", "Catalog");
            }

            ViewBag.ChemicalCompositionId = new SelectList(db.ChemicalCompositions, "Id", "Title", sample.ChemicalCompositionId);
            return View(sample);
        }

        // GET: Samples/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sample sample = db.Samples.Find(id);
            if (sample == null)
            {
                return HttpNotFound();
            }
            ViewBag.ChemicalCompositionId = new SelectList(db.ChemicalCompositions, "Id", "Title", sample.ChemicalCompositionId);
            return View(sample);
        }

        // POST: Samples/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,ChemicalCompositionId,Amount,ImageLink,Weight,ExpiryDate")] Sample sample)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sample).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ChemicalCompositionId = new SelectList(db.ChemicalCompositions, "Id", "Title", sample.ChemicalCompositionId);
            return View(sample);
        }

        // GET: Samples/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sample sample = db.Samples.Find(id);
            if (sample == null)
            {
                return HttpNotFound();
            }
            return View(sample);
        }

        // POST: Samples/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sample sample = db.Samples.Find(id);
            db.Samples.Remove(sample);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SupplyManagementSystem/Views/Samples/Create.cshtml
@model SCM.Models.Sample

@{
    ViewBag.Title = "Добавить новый образец";
}

<h2>Добавить новый образец</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Образец</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChemicalCompositionId, "Химический состав", htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.DropDownList("ChemicalCompositionId", null, htmlAttributes: new { @class = "form-control chosen-select" })
                @Html.ValidationMessageFor(model => model.ChemicalCompositionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageLink, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.ImageLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-12" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

SupplyManagementSystem/Views/Samples/Delete.cshtml
@model SCM.Models.Sample

@{
    ViewBag.Title = "Удаление образца";
}

<h2>@Model.Title</h2>

<h3>Вы уверены что хотите удалить образец @Model.Title ?</h3>
<div>
    <h4>Образец</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChemicalComposition.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChemicalComposition.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

SupplyManagementSystem/Views/Samples/Details.cshtml
@model SCM.Models.Sample

@{
    ViewBag.Title = "Подробности";
}

<h2>@Model.Title</h2>

<div>
    <h4>@Model.Title</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ChemicalComposition.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChemicalComposition.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageLink)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpiryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpiryDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

SupplyManagementSystem/Views/Samples/Edit.cshtml
@model SCM.Models.Sample

@{
    ViewBag.Title = "Редактировать";
}

<h2>@Model.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.Title</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChemicalCompositionId, "ChemicalCompositionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ChemicalCompositionId", null, htmlAttributes: new { @class = "form-control chosen-select" })
                @Html.ValidationMessageFor(model => model.ChemicalCompositionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpiryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpiryDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SupplyManagementSystem/Views/Samples/Index.cshtml
@using Kendo.Mvc.UI
@using SCM.Models
@using SCM.ViewModels.Samples
@model IEnumerable<SCM.ViewModels.Samples.SamplesGridModel>

@{
    ViewBag.Title = "Образцы";
}

<h1>Образцы</h1>

<div class="container-fluid">
    <div class="row">
        @(Html.Kendo().Grid<SamplesGridModel>()
              .Resizable(c => c.Columns(true))
              .Name("grid")
              .Columns(columns =>
              {
                  columns.Bound(p => p.Title).Title("Образец");
                  columns.Bound(p => p.FormatDate).Title("Срок годности");
                  columns.Bound(p => p.ChemicalCompositionAsString).Title("Хим. состав");
                  columns.Bound(p => p.Amount).Title("Количество на складе");
                  columns.Bound(p => p.Weight).Title("Вес образца");
                  columns.Bound(p => p.Id).Title("Действия").ClientTemplate("<a href='" + @Url.Action("Edit", "Samples", new {id = "#=Id#"}) + "' class='btn btn-xs'>  <i class='fas fa-pen'></i></a>" + "<a href='" + @Url.Action("Delete", "Samples", new {id = "#=Id#"}) + "' class='btn btn-xs m-1'>  <i class='fas fa-trash'></i></a> ");
              })
              .Pageable()
              .Groupable()
              .Sortable()
              .Scrollable(s => s.Enabled(true))
              .ToolBar(t =>
              {
                  t.Custom().Url(Url.Action("Create")).HtmlAttributes(new {@class = "float-right"}).Text("Добавить образец");
                  t.Excel().Text("Экспортировать в Эксель");
              })
              .Excel(excel => excel
                  .FileName("Образцы.xlsx")
                  .Filterable(true)
                  .ProxyURL(Url.Action("ExportExcel", "Excel"))
              )
              .Filterable()
              .DataSource(dataSource => dataSource
                  .Ajax()
                  .PageSize(10)
                  .Read(read => read.Action("SamplesRead", "Samples"))
              ))
    </div>
</div>