SupplyManagementSystem/Models/SampleCategory.cs
using SCM.Core;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using SCM.Domain.Enums;

namespace SCM.Models
{
    [DisplayName("Категория образцов")]
    public class SampleCategory : Entity
    {
        [DisplayName("Наименование категории")]
        public new string Title { set; get; }
        
        
        [DisplayName("Базовые химические элементы")]
        public virtual ICollection<ChemicalElement> ChemicalElements { get; set; }

        [DisplayName("Область применения образцов")]
        public SampleCategoryType SampleCategoryType { get; set; }
        
        [DisplayName("Ссылка на картинку")]
        public string ImageLink { get; set; }
    }
}

SupplyManagementSystem/ViewModels/SampleCategory/CreateSampleCategoryViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Web;

namespace SCM.ViewModels.SampleCategory
{
    public class CreateSampleCategoryViewModel
    {
        /// <summary>
        /// Наименование категории
        /// </summary>
        [DisplayName("Наименование категории")]
        public string Title { set; get; }

        /// <summary>
        /// Перечень базовых химических элементов
        /// </summary>
        [DisplayName("Перечень базовых химических элементов")]
        public int[] BaseChemicalElementId { get; set; }
        
        //To change label title value  
        [DisplayName("Ссылка на изображение")]  
        public string ImageLink { get; set; }  

    }
}

SupplyManagementSystem/Controllers/SampleCategoryController.cs
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Kaliko.ImageLibrary;
using SCM.DataService.DataContext;
using SCM.Models;
using SCM.ViewModels.SampleCategory;
using WebApp.Infrastructure;

namespace SCM.Controllers
{
    [Authorize]
    public class SampleCategoryController : Controller
    {
        public ActionResult Create()
        {
            var vm = new CreateSampleCategoryViewModel();
            return View(vm);
        }
        
        
        [HttpPost]
        public ActionResult Create(CreateSampleCategoryViewModel model)
        {
            var context = new AppDataContext();
            var elements = model.BaseChemicalElementId != null && model.BaseChemicalElementId.Any()
                ? context.ChemicalElements.Where(e => model.BaseChemicalElementId.Contains(e.Id)).ToList() : new List<ChemicalElement>();
            var category = new SampleCategory
            {
                Title = model.Title, ChemicalElements = elements, ImageLink = model.ImageLink
            };
            context.Add(category);
            context.Commit();
            return RedirectToAction("Index", "Catalog");
        }

        private void ResolveViewBag()
        {
            var context = new AppDataContext();

            var accessableChemicalElements = context.ChemicalElements.Select(element => new SelectListItem()
                {Text = element.Symbol +"-" +element.Title, Value = element.Id.ToString()}).OrderBy(option => option.Text);
            var chemicalElementsMultiSelect = new MultiSelectList(accessableChemicalElements, "Value", "Text");
            ViewBag.ChemicalElementsMultiSelect = chemicalElementsMultiSelect;
        }


        protected override void OnResultExecuting(ResultExecutingContext filterContext)
        {
            ResolveViewBag();
            base.OnResultExecuting(filterContext);
        }
    }
}

SupplyManagementSystem/Views/SampleCategory/Create.cshtml
@model SCM.ViewModels.SampleCategory.CreateSampleCategoryViewModel

@{
    ViewBag.Title = "Создание категории";
    var elements = (MultiSelectList)ViewBag.ChemicalElementsMultiSelect;
}



<h2>Создание категории</h2>

@using (Html.BeginForm("Create", "SampleCategory", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-6" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageLink, htmlAttributes: new { @class = "control-label col-md-6" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.ImageLink, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ImageLink, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BaseChemicalElementId, htmlAttributes: new { @class = "control-label col-md-6" })
            <div class="col-md-12">
                @Html.ListBoxFor(m => m.BaseChemicalElementId, elements, new { multiple = "multiple", @class="chosen-select", placeholder="ВЫберите элементы"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-dark-light" />
            </div>
        </div>
    </div>
}